import React from 'react';
import FilterBlueprints from '@/components/blueprint/FilterBlueprints';
import { baseURL } from '@/lib/api/baseUrl';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Explore Blueprints - Archflow',
  description:
    'Browse production-ready community architecture blueprints generated by autonomous AI agents, ready for Cursor, Windsurf, and Claude Code.',
};

export default async function ExplorePage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | undefined }>;
}) {
  const params = await searchParams;
  const currentPage = Number(params.page) || 1;
  const search = params.search || '';
  const stack = params.stack || 'All';
  const sort = params.sort || 'newest';

  // 20 cards per page
  const query = new URLSearchParams({ page: String(currentPage), limit: '20' });
  if (search.trim()) query.set('search', search.trim());
  if (stack && stack !== 'All') query.set('stack', stack);
  if (sort && sort !== 'newest') query.set('sort', sort);

  let blueprints: any[] = [];
  let totalPage = 1;
  let totalData = 0;

  try {
    const res = await fetch(`${baseURL}/api/all-blueprints?${query.toString()}`, {
      cache: 'no-store',
    });
    if (res.ok) {
      const data = await res.json();
      blueprints = Array.isArray(data.data) ? data.data : (Array.isArray(data.blueprints) ? data.blueprints : []);
      totalPage = data.totalPage || data.totalPages || 1;
      totalData = data.totalData !== undefined ? data.totalData : (data.total !== undefined ? data.total : blueprints.length);
    }
  } catch (err) {
    console.error('Failed to fetch blueprints on server:', err);
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 flex-grow">
      <FilterBlueprints
        allBlueprints={blueprints}
        totalData={totalData}
        currentPage={currentPage}
        totalPages={totalPage}
        currentSearch={search}
        currentStack={stack}
        currentSort={sort}
      />
    </div>
  );
}
