import React from 'react';
import FilterBlueprints from '@/components/explore/FilterBlueprints';
import PaginationControls from '@/components/Pagination';
import { baseURL } from '@/lib/api/baseUrl';
import { Layers } from 'lucide-react';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Explore Blueprints - Archflow',
  description:
    'Browse production-ready community architecture blueprints generated by autonomous AI agents, ready for Cursor, Windsurf, and Claude Code.',
};

export default async function ExplorePage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | undefined }>;
}) {
  const params = await searchParams;
  const currentPage = Number(params.page) || 1;
  const search = params.search || '';
  const stack = params.stack || 'All';
  const complexity = params.complexity || 'All';
  const sort = params.sort || 'newest';

  const query = new URLSearchParams({ page: String(currentPage), limit: '6' });
  if (search.trim()) query.set('search', search.trim());
  if (stack && stack !== 'All') query.set('stack', stack);
  if (complexity && complexity !== 'All') query.set('complexity', complexity);
  if (sort) query.set('sort', sort);

  let blueprints: any[] = [];
  let totalPage = 1;
  let totalData = 0;

  try {
    const res = await fetch(`${baseURL}/api/all-blueprints?${query.toString()}`, {
      cache: 'no-store',
    });
    if (res.ok) {
      const data = await res.json();
      blueprints = Array.isArray(data.data) ? data.data : (Array.isArray(data.blueprints) ? data.blueprints : []);
      totalPage = data.totalPage || data.totalPages || 1;
      totalData = data.totalData !== undefined ? data.totalData : (data.total !== undefined ? data.total : blueprints.length);
    }
  } catch (err) {
    console.error('Failed to fetch blueprints on server:', err);
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 flex-grow">
      {/* Header section */}
      <div className="mb-8 space-y-2">
        <div className="inline-flex items-center gap-2 rounded-full bg-[#EEF0FF] dark:bg-[#4F46E5]/15 border border-[#4F46E5]/30 px-3.5 py-1 text-xs font-semibold text-[#4F46E5] dark:text-[#818CF8] uppercase tracking-wider">
          <Layers className="h-3.5 w-3.5" />
          <span>Architectural Community Gallery</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-[#181B20] dark:text-[#F3F4F6] font-display">
          Explore AI Blueprints
        </h1>
        <p className="text-xs sm:text-sm text-[#6B7280] dark:text-[#9CA3AF]">
          Browse {totalData > 0 ? `${totalData} production` : 'community'} architecture suites ready for Cursor, Windsurf, and Claude Code.
        </p>
      </div>

      {/* Filter & Blueprints Grid Component */}
      <FilterBlueprints
        allBlueprints={blueprints}
        currentSearch={search}
        currentStack={stack}
        currentComplexity={complexity}
        currentSort={sort}
      />

      {/* Pagination Controls — sits at the bottom of the card grid */}
      <div className="mt-10">
        <PaginationControls currentPage={currentPage} totalPages={totalPage} />
      </div>
    </div>
  );
}
