'use client';

import React, { useState, useEffect } from 'react';
import Refresh from '@/components/explore/Refresh';
import SearchFilterControls from '@/components/explore/SearchFilterControls';
import BlueprintCard from '@/components/BlueprintCard';
import SkeletonCard from '@/components/ui/SkeletonCard';
import Pagination from '@/components/Pagination';
import { getAllBlueprints } from '@/lib/api/server';
import { SlidersHorizontal } from 'lucide-react';

interface Blueprint {
  _id: string;
  title: string;
  description: string;
  shortDescription?: string;
  stack?: string;
  teckStack?: string | string[];
  complexity?: string;
  complexcity?: string;
  rating?: number;
  status: string;
  createdAt?: string;
  Date?: string;
}

export default function ExplorePage() {
  const [blueprints, setBlueprints] = useState<Blueprint[]>([]);
  const [loading, setLoading] = useState(true);

  // Search & Filters state
  const [search, setSearch] = useState('');
  const [stackFilter, setStackFilter] = useState('All');
  const [complexityFilter, setComplexityFilter] = useState('All');
  const [sortBy, setSortBy] = useState('newest');

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 4;

  const fetchBlueprints = async () => {
    setLoading(true);
    try {
      const data = await getAllBlueprints();
      if (data) {
        setBlueprints(data);
      }
    } catch (err) {
      console.error('Error fetching blueprints:', err);
    } finally {
      // Small timeout for premium visual transition
      setTimeout(() => {
        setLoading(false);
      }, 500);
    }
  };

  useEffect(() => {
    fetchBlueprints();
  }, []);

  // Helpers
  const getStackText = (bp: Blueprint) => {
    if (bp.stack) return bp.stack;
    if (bp.teckStack) {
      if (Array.isArray(bp.teckStack)) return bp.teckStack.join(' + ');
      return bp.teckStack;
    }
    return '';
  };

  const getComplexityText = (bp: Blueprint) => {
    return bp.complexity || bp.complexcity || 'Medium';
  };

  // Filter & Search Logic
  const filteredBlueprints = blueprints
    .filter((bp) => {
      const title = bp.title || '';
      const desc = bp.description || '';
      const shortDesc = bp.shortDescription || '';
      const stack = getStackText(bp);
      const complexity = getComplexityText(bp);

      const matchSearch =
        title.toLowerCase().includes(search.toLowerCase()) ||
        desc.toLowerCase().includes(search.toLowerCase()) ||
        shortDesc.toLowerCase().includes(search.toLowerCase());

      const matchStack =
        stackFilter === 'All' ||
        stack.toLowerCase().includes(stackFilter.toLowerCase());

      const matchComplexity =
        complexityFilter === 'All' ||
        complexity.toLowerCase() === complexityFilter.toLowerCase();

      return matchSearch && matchStack && matchComplexity;
    })
    .sort((a, b) => {
      const dateA = a.createdAt || a.Date || '';
      const dateB = b.createdAt || b.Date || '';
      const ratingA = a.rating || 0;
      const ratingB = b.rating || 0;

      if (sortBy === 'newest') {
        return new Date(dateB).getTime() - new Date(dateA).getTime();
      } else if (sortBy === 'rating') {
        return ratingB - ratingA;
      }
      return 0;
    });

  // Pagination Logic
  const totalItems = filteredBlueprints.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const paginatedBlueprints = filteredBlueprints.slice(startIndex, startIndex + itemsPerPage);

  // Reset page on search/filter changes
  useEffect(() => {
    setCurrentPage(1);
  }, [search, stackFilter, complexityFilter, sortBy]);

  return (
    <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 flex-grow">
      {/* Page Header */}
      <div className="mb-12 text-center md:text-left md:flex md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-[#181B20] font-display">
            Explore Architecture Blueprints
          </h1>
          <p className="mt-2 text-sm text-[#6B7280]">
            Search, filter, and review technical plans generated by the
            multi-agent AI pipeline.
          </p>
        </div>

        <Refresh onRefresh={fetchBlueprints} loading={loading} />
      </div>

      <SearchFilterControls
        search={search}
        setSearch={setSearch}
        stackFilter={stackFilter}
        setStackFilter={setStackFilter}
        complexityFilter={complexityFilter}
        setComplexityFilter={setComplexityFilter}
        sortBy={sortBy}
        setSortBy={setSortBy}
      />

      {/* Listing Grid */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {Array.from({ length: itemsPerPage }).map((_, idx) => (
            <SkeletonCard key={idx} />
          ))}
        </div>
      ) : paginatedBlueprints.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-xl border border-[#E1E4EA]">
          <SlidersHorizontal className="mx-auto h-12 w-12 text-[#6B7280] mb-4" />
          <h3 className="text-lg font-bold text-[#181B20] font-display">
            No blueprints found
          </h3>
          <p className="text-sm text-[#6B7280] mt-1">
            Try adjusting your search query or filter parameters.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {paginatedBlueprints.map((bp) => (
            <BlueprintCard key={bp._id} blueprint={bp} />
          ))}
        </div>
      )}

      {/* Pagination Controls */}
      {!loading && (
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={setCurrentPage}
        />
      )}
    </div>
  );
}
